ramaSanmartín
FPGS/AndroidBubble pull request #5
Opened 2017-10-03 20:36 UTC by iSanmartin8a

2017-10-05 08:22 UTC, JoTerrance reviewed
revisa los comentarios y haz los cambios oportunos

2017-10-05 08:22 UTC, JoTerrance commented on app/src/main/java/com/mirallax/android/bubble/FrozenGame.java
> +        public void setHorizontal_Move(int HORIZONTAL_MOVE)
tener gettes lo veo bien
tener setters no, porque no hay ninguna opcion de reconfigurar las teclas
getHorizontal_Move deberia llamarse getHorizontalMove
getKey_UP deberia llamarse getKeyUp
y así con todos

2017-10-05 20:15 UTC, JoTerrance requested changes
realiza los cambios comentados

2017-10-16 09:48 UTC, iSanmartin8a commented
Ya esta arreglado.

2017-10-16 09:51 UTC, iSanmartin8a commented
Perdoname.

2017-10-19 09:37 UTC, merged